### ISSUE TITLE
Check your invironment and configuration 

### ISSUE THREAD

**Issue by abdozekaa** [dana-at-cp/backdoor-apk#125]
I am running on kali nethunter and i get this issue 
![screenshot_20171110-051301](https://user-images.githubusercontent.com/24819172/32641322-dd45356e-c5d5-11e7-9c06-f95bb9a113b2.png)

**Comment by dana-at-cp** [comment]
@abdozekaa I'm guessing Kali nethunter doesn't have dex2jar installed by default or it has a different name or path?

**Comment by abdozekaa** [comment]
Am new .. so what should i do 
Am so sorry for the late

**Comment by r4z0r5** [comment]
Also note that ProGuard is now 5.3.3, the tool is still looking for 5.3.2

**Comment by wh001s** [comment]
Hi, I have similar issue running on kali 2.0

"Check your environment and configuration. Couldn't find: jarsigner"

even though JDK is installed java -version output is: 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

kernel headers are installed

any ideas?

EDIT:
never mind, I edited the script and manually entered jarsigner path.

Another issue is "Failed to copy RAT smali files", happens with any apk I heave tried.

run.log:
mkdir: created directory '/root/backdoor-apk/backdoor-apk/original/smali/us'
mkdir: created directory '/root/backdoor-apk/backdoor-apk/original/smali/us/sigma'
mkdir: created directory '/root/backdoor-apk/backdoor-apk/original/smali/us/sigma/ias'
cp: cannot stat '/root/backdoor-apk/backdoor-apk/payload/smali/com/metasploit/stage/MainBroadcastReceiver.smali': No such file or directory
Forcing cleanup due to a failure or error state!

**Comment by HongLuDianXue** [comment]
me too...

**Comment by SagarspTEE** [comment]
How to fix couldn't find:d2j-dex2jar on Kali Linux I have downloaded this file but I'm unable to run help me..

**Comment by dana-at-cp** [comment]
Can't support environment issues. Sorry.
