### ISSUE TITLE
Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by Morteda** [dana-at-cp/backdoor-apk#141]
Failed to recompile original project with backdoor how can solved it plz 
😐
Apktool the last version 2.3.3

**Comment by Morteda** [comment]
No answer 😐

**Comment by frovaaa** [comment]
i have the same problem

**Comment by glenn2148** [comment]
i have seen this on many forums and no one has come to a complete and reliable fix,i have tryed everything suggested in all forums and no progress in fixing it, backdoor-apk needs to be taken down.

**Comment by waleed99100** [comment]
check  new issues i solved common problems

**Comment by dana-at-cp** [comment]
@Morteda @dravid3x @glenn2148 @waleed99100 Many of these types of issues are a result of Apktool not being able to recompile the original APK. As a quick test, use Apktool to decompile and recompile the APK. If Apktool fails then the issue is with the APK and/or Apktool. If Apktool decompiles/recompiles the APK successfully then there may be an issue within backdoor-apk.sh.
